### ISSUE TITLE
Verion number in ??2 files

### ISSUE THREAD

**Issue by lscheffler** [fdbozzo/foxbin2prg#10]
The version number in the ??2 files is just _nn.nn_

It would be better to have _nn.nn.nn_, or since you use this in git _nn.nn.nn.nn_ so one can
- go back to a working  version
- give better description of error

**Comment by fdbozzo** [comment]
Hi Lutz:

I can't really get what you mean with "_The version number in the ??2 files is just nn.nn_"

You mean this internal comment line?

*< FOXBIN2PRG: Version="1.19" SourceFile="lib1.vcx" /> (Solo para binarios VFP 9 / Only for VFP 9 binaries)

or you mean another thing? Please, use an example.

Thanks!

**Comment by lscheffler** [comment]
Exactly this line.

It's the same for _1.19.48_ as well as for _1.19.49_ as for _1.19.49.1_

For whatever reason the newest version is not responding at all - bug report later - and I need a fast fix. It would be nice to know what version was the last working (with me) so I could go back.

The problem is, distributing through _git pull_ simply goes fgorward without any trace of lsat status.

**Comment by fdbozzo** [comment]
Hi Lutz,

This line can't be changed because if I do it (as I did when starting) then EVERY TX2 regeneration will change this, even if you don't modify the binary, causing a LOT of generated files because when comparing this TX2 with the previous one, FoxBin2Prg will assume that they are different (because if this version mark) then will overwrite the original file.

**Comment by lscheffler** [comment]
Yes, this should happen.  This is one commit with just one line change per file, not a big problem. Every time I touch my pictures I store more data.

Also, Bin2Prg will create the tx2 file only when the binary is touched (tested by a hash), so it will not generate it just for version change.

**Comment by fdbozzo** [comment]
Well, may be in your scenario this could be not a problem, but when using with another implementations it is a big one. Even if anyone converts a single file with FoxBin2Prg directly (ie: using the "SendTo" shortcut), then the TX2 would be generated because of this. It's more a headache than a feature, not a good idea for me.

**Comment by lscheffler** [comment]
No problem in general, only then version is superflous at all. For me it would have been a great benefit to figure out what version is working, because I miss the time to debug (whatever is wrong, I guess my code with something changed in your execute method) So I was crawling backwards for two hours until it worked again.

**Comment by fdbozzo** [comment]
Lutz, tell me what is not working for you in the latest version, something I can replicate with a test, and I will look for a fix if it is a bug. Once I know what to test, I will compare it with the v1.19.48 to see if there is a regression.
In our daily use with the program, did not find any problem going between binaries and tx2.

Thanks!

**Comment by lscheffler** [comment]
Hi Fernando - I go over to issue #9 with this
