### ISSUE TITLE
After recreating pjx file, text files are moved from Text files to Other files

### ISSUE THREAD

**Issue by dkeza** [fdbozzo/foxbin2prg#21]
When I have some text files in [project](https://github.com/dkeza/vfp_test_for_foxbin2prg), and keep these in Text files section
![bild-1](https://user-images.githubusercontent.com/12168379/37451526-16c558d2-2832-11e8-822f-73157c011808.png)
and then I create pjm file with foxbin2prg.exe
![bild-2](https://user-images.githubusercontent.com/12168379/37451562-30b9ff54-2832-11e8-89c5-1e91dffdc10c.png)
when I later recreate my pjx file from pjm file, those text files are now in Other files, instead in Text files section, in my project
![bild-3](https://user-images.githubusercontent.com/12168379/37451610-4d658f6a-2832-11e8-9368-7a0465504d56.png)

Is maybe there some parameter to disable this behavior?

Thank you

**Comment by fdbozzo** [comment]
Hi Darko,

I can confirm that's a bug. Non-habitual file types included in the project are not handled correctly.
Will fix it in next patch v1.19.50.3

Thanks for reporting! :)

**Comment by fdbozzo** [comment]
Thanks for the proposal Darko!

But in this case this is a real bug because the PJX should keep the user selection, so if you add those files in the text section or in the files section, the PJX should respect that.
You may prefer (as I do) to keep all text files in the text section, but someone else may prefer to add them on the files section.

The fox for this is replacing the last line:
, 'x' )

with this:
, EVL(tcOriginalType, 'x') )

I will modify it tonight, at home.

**Comment by fdbozzo** [comment]
By the way:

FXP's shouldn't be added in the PJX because they are object code, not source code. PRG's (sources) should only be added.
When you create an EXE or APP or DLL, the compiled FXP versions of their corresponding PRG files are included automatically in the EXE/APP/DLL generated file.

In the case of non-VFP files, like HTML, CSS, etc, if you only want to "reference" that those files correspond to this project but you don't really want to include the contents of those files in the generated EXE/APP/DLL, then you should mark them in the project as "Excluded", because otherwise all the content of all those files is included too, making the generated EXE/APP/DLL big and slow, and you can have some trouble accessing those files from VFP, because if they are full-included then are marked as readonly internally.

I tell you this just in case, because it's not common to add those files in a VFP project.

Best Regards!

**Comment by fdbozzo** [comment]
Hi Darko:

It's fixed in [v1.19.50.3](https://github.com/fdbozzo/foxbin2prg/tree/v1.19.50.3)

Best Regards!

**Comment by dkeza** [comment]
I checked it with new version, and it works now. Thank you!

Regarding including fxp file in project, I have only one such fxp file, xfrx.fxp, which is third party module for generating reports, and i prefer to include it in exe, to prevent issues with different versions on customer site and in my testing environment.
I have one project which acts as small web server, and it is VFP exe, and in this case I also prefer to have all files in exe, to prevent somebody to edit html, js etc. files :)

**Comment by fdbozzo** [comment]
Ok, that's a good use case :-)
