### ISSUE TITLE
OLE error code 0x80030050: Unknown COM status code.

### ISSUE THREAD

**Issue by dkeza** [fdbozzo/foxbin2prg#23]
I have some vcx file in my test [project](https://github.com/dkeza/vfp_test_for_foxbin2prg
), which has OLE control class. Now I convert this class to text file. When I try to convert it back to binary, at first everything seems alright.
But, when I try to modify this class, I receive error
```
OLE error code 0x80030050: Unknown COM status code.
```

![picture_1](https://user-images.githubusercontent.com/12168379/37470036-e7aa2fe8-2866-11e8-927d-1933ae98cb66.png)

In test project is in before folder _datetime.vcx before conversion to text file.

**Comment by fdbozzo** [comment]
Hi Darko:

I think something is wrong in your setup or something did not save ok on VFP when closing the classlibrary, because I can open your library, export to text, back to vcx and open it again.

But found that when converting to text your library, the generated text is a little different than yours.

I'm attaching my generated vca from your library (take out the ".log" part) and see if works on your setup.

[_datetime.vca.log](https://github.com/fdbozzo/foxbin2prg/files/1816143/_datetime.vca.log)

All I did was:
- Regenerate all binaries
- Copy your library to pjx folder (overwriting the generated from last step)
- Regenerate the text for this library
- Regeneraye the library from the generated text
- Open the class library on VFP again

If my attached vca works ok when converting to binary, then try regenerating from the vcx, back to binary and opening again.

A little hint:
Each time yo save a classlibrary in VFP, it's better to do it with CTRL+W (save&close) or CTRL+S (save) or even with the "Save" menu, but do not close it directly with the "X", because sometimes does not save ok this way.

**Comment by dkeza** [comment]
Ok, I got it :)

I changed code page for non unicode programs in Windows from Serbian to German, and it works now

![picture_1](https://user-images.githubusercontent.com/12168379/37490975-8f7b1c52-289c-11e8-9814-bba1d57dec36.png)

That means, it works with Code Page 1252, but it doesn't work with 1250 (Central Europe).

I have also seen differences some times in comment in text files:
```
*--------------------------------------------------------------------------------------------------------------------------------------------------------
* (ES) AUTOGENERADO - ¡¡ATENCIÓN!! - ¡¡NO PENSADO PARA EJECUTAR!! USAR SOLAMENTE PARA INTEGRAR CAMBIOS Y ALMACENAR CON HERRAMIENTAS SCM!!
* (EN) AUTOGENERATED - ATTENTION!! - NOT INTENDED FOR EXECUTION!! USE ONLY FOR MERGING CHANGES AND STORING WITH SCM TOOLS!!
*--------------------------------------------------------------------------------------------------------------------------------------------------------
```
This non standard characters Ó and ¡ are some times on my PC, with Code Page 1250, not showed correctly, and I see differences.

Maybe I should force Code Page 1252 in config.fpw for foxbin2prg.exe
```
CodePage=1252
```
?

**Comment by fdbozzo** [comment]
Wow, never tested with another code page! Yeah, I suppose that can be fixed with this. It's a good idea.

**Comment by fdbozzo** [comment]
Ok, I did add the codepage in internal CFG and in a new external one for the Development PRG version.

You will find them on https://github.com/fdbozzo/foxbin2prg (not labeled)

One config.fpw is on main dir, and the other in \config dir (which es used by the EXE)

Let me know if this fixes the problem with the codepage.

**Comment by dkeza** [comment]
I used new version with code page hard coded in config.fpw which is included in foxbin2prg.exe, and it works now.
