### ISSUE TITLE
Problem with sorting property and outlooknavbar (ThemedControls)

### ISSUE THREAD

**Issue by JochenKauz** [fdbozzo/foxbin2prg#28]
Hi,
I use in one of my projects the outlooknavbar. If I use bin2text and then text2bin, the overflowpanel is always collapsed and the defined Panels are not shown correctly.
I looked at the code of foxbin2prg and found out that I can make it function correctly by disabling l_PropSort_Enabled.
The problem is caused by the init order of the child objects in the outlooknavbar. The splitter object has to be added before the panes object, but the sort destroys this.
For properties I can change the sorting order, but not for the objects.
Wrong Order:
```
ADD OBJECT 'Themedoutlooknavbar' AS themedoutlooknavbar WITH ;
		Comment = "<NORESIZE>", ;
		displayshrinkbutton = .T., ;
...
		overflowpanel.HelpContextID = 201010, ;
		overflowpanel.Left = 0, ;
...
		Panel.HelpContextID = 201010, ;
		Panel.Left = 0, ;
...
		panelvertical.Anchor = 5, ;
		panelvertical.Enabled = .F., ;
...
		panes.Anchor = 15, ;
		panes.ErasePage = .T., ;
...
		panes.Pane1.Caption = "Adressen", ;
		panes.Pane1.HelpContextID = 201010, ;
...
		panes.Pane2.Caption = "Kontakte", ;
		panes.Pane2.HelpContextID = 201010, ;
...
		panes.Pane3.Caption = "Auftragsbearbeitung", ;
		panes.Pane3.HelpContextID = 201010, ;
...
		panes.Pane4.Caption = "Kartendarstellung", ;
		panes.Pane4.HelpContextID = 201410, ;
...
		panes.Top = 28, ;
		panes.Width = 198, ;
		shrinkbutton.HelpContextID = 201010, ;
		shrinkbutton.Name = "shrinkbutton", ;
		Splitter.HelpContextID = 201010, ;
		Splitter.imgBackground.Name = "imgBackground", ;
...
		Title.HelpContextID = 201010, ;
		Title.imgBackground.Name = "imgBackground", ;
...
		*< END OBJECT: ClassLib="..\lib\themedcontrols.vcx" BaseClass="container" />
```
Correct order:
```
	ADD OBJECT 'Themedoutlooknavbar' AS themedoutlooknavbar WITH ;
		Comment = "<NORESIZE>", ;
		displayshrinkbutton = .T., ;
...
		panelvertical.Anchor = 5, ;
		panelvertical.Enabled = .F., ;
...
		Title.HelpContextID = 201010, ;
		Title.imgBackground.Name = "imgBackground", ;
...
		overflowpanel.HelpContextID = 201010, ;
		overflowpanel.Left = 0, ;
...
		shrinkbutton.HelpContextID = 201010, ;
		shrinkbutton.Name = "shrinkbutton", ;
		Panel.HelpContextID = 201010, ;
		Panel.Left = 0, ;
...
		Splitter.HelpContextID = 201010, ;
		Splitter.imgBackground.Name = "imgBackground", ;
...
		panes.Anchor = 15, ;
		panes.ErasePage = .T., ;
...
		panes.Pane1.Caption = "Adressen", ;
		panes.Pane1.HelpContextID = 201010, ;
...
		panes.Pane2.Caption = "Kontakte", ;
		panes.Pane2.HelpContextID = 201010, ;
...
		panes.Pane3.Caption = "Auftragsbearbeitung", ;
		panes.Pane3.HelpContextID = 201010, ;
...
		panes.Pane4.Caption = "Kartendarstellung", ;
		panes.Pane4.HelpContextID = 201410, ;
...
		panes.Top = 28, ;
		panes.Width = 198, ;
...
		*< END OBJECT: ClassLib="..\lib\themedcontrols.vcx" BaseClass="container" />
```

Best regards
JochenKauz

**Comment by fdbozzo** [comment]
Hi Jochen:

I must see this very carefuly, because taking out the sort can produce a lot of differences in many parts of the classes, depending what you use.
I will take a deep look to find a solution and will make a comment here when I have it.

Thanks for reporting!

**Comment by JochenKauz** [comment]
Hi Fernando,
thanks for your support!
I know that this is a tricky thing, cause not sorting would produce in other circumstances different result in diffs.
I have 2 ideas after looking in the code:
1. splitting the array to make a difference between properties and objects. Then sort all properties of the objects in the order the objects appear. This would not be failsafe, I think.
2. splitting the array to make a difference between properties and objects. Implement a similar process for objects, like for the properties. If nothing is defined in a special file, alphabetical order is used, but it is possible to define exceptions, best it would be in a cfg in the directory processed. This would give a user the chance to define custom sort orders if needed in every directory. ThemedControls would be not an exception, cause they really depends on init sequence.
If I could help, please give me a message.

**Comment by fdbozzo** [comment]
Hi Jochen,

Very thanks for your ideas!
I think that a compromise solution can be done using the option 1 you suggest, but with some more object/property processing.

The thing is this:

a) Objects must appear in the same order as the do in the original source

b) Properties must appear (in text) alphabetically ordered to not cause "differences" when diffing with previous modifications

Changing the order from actual (sorted) object names to original order probabli will cause many differences, but even this case can be improved if at least all objects with the same name are grouped.

In example, you can have a binary file which code is saved in a way in which objects appear in a specific order, but ungrouped, like this:

<pre>
	ADD OBJECT 'Themedoutlooknavbar' AS themedoutlooknavbar WITH ;
		Comment = "<NORESIZE>", ;
		displayshrinkbutton = .T., ;
		panelvertical.Enabled = .F., ;
		Title.imgBackground.Name = "imgBackground", ;
		overflowpanel.HelpContextID = 201010, ;
		overflowpanel.Left = 0, ;
		panelvertical.Anchor = 5, ;
		shrinkbutton.HelpContextID = 201010, ;
		Panel.HelpContextID = 201010, ;
		Panel.Left = 0, ;
		Splitter.HelpContextID = 201010, ;
		Title.HelpContextID = 201010, ;
		Splitter.imgBackground.Name = "imgBackground", ;
		panes.Anchor = 15, ;
		shrinkbutton.Name = "shrinkbutton", ;
		panes.ErasePage = .T., ;
		panes.Pane1.HelpContextID = 201010, ;
		panes.Pane2.HelpContextID = 201010, ;
		panes.Pane3.Caption = "Auftragsbearbeitung", ;
		panes.Pane2.Caption = "Kontakte", ;
		panes.Pane3.HelpContextID = 201010, ;
		panes.Pane4.Caption = "Kartendarstellung", ;
		panes.Pane1.Caption = "Adressen", ;
		panes.Pane4.HelpContextID = 201410, ;
		panes.Top = 28, ;
		panes.Width = 198, ;
		*< END OBJECT: ClassLib="..\lib\themedcontrols.vcx" BaseClass="container" />
</pre>

I can't do the full alphabetical order because of the error you reported, but I can group the same objects together and sort their properties alpabetically, so they appear this way when in text form:

<pre>
	ADD OBJECT 'Themedoutlooknavbar' AS themedoutlooknavbar WITH ;
		Comment = "<NORESIZE>", ;
		displayshrinkbutton = .T., ;
		panelvertical.Anchor = 5, ;
		panelvertical.Enabled = .F., ;
		Title.HelpContextID = 201010, ;
		Title.imgBackground.Name = "imgBackground", ;
		overflowpanel.HelpContextID = 201010, ;
		overflowpanel.Left = 0, ;
		shrinkbutton.HelpContextID = 201010, ;
		shrinkbutton.Name = "shrinkbutton", ;
		Panel.HelpContextID = 201010, ;
		Panel.Left = 0, ;
		Splitter.HelpContextID = 201010, ;
		Splitter.imgBackground.Name = "imgBackground", ;
		panes.Anchor = 15, ;
		panes.ErasePage = .T., ;
		panes.Pane1.Caption = "Adressen", ;
		panes.Pane1.HelpContextID = 201010, ;
		panes.Pane2.Caption = "Kontakte", ;
		panes.Pane2.HelpContextID = 201010, ;
		panes.Pane3.Caption = "Auftragsbearbeitung", ;
		panes.Pane3.HelpContextID = 201010, ;
		panes.Pane4.Caption = "Kartendarstellung", ;
		panes.Pane4.HelpContextID = 201410, ;
		panes.Top = 28, ;
		panes.Width = 198, ;
		*< END OBJECT: ClassLib="..\lib\themedcontrols.vcx" BaseClass="container" />
</pre>

This order coincidentally is like you posted, but I have some other code examples I that have the disorder I shown in the 1st example, because VFP do not always keep things ordered and clean.

Finally, when assembling the binary again from text, then a special property order must applied because inside the VCX/SCX, VFP native properties can't be alphabetically ordered, and have a specific order, because if not, then Strange Things happen.

So the hard part on this grouping (maintaining the original order) is that must be done on objectName basis, from first to last level of nesting:

a) Taking note on the original order of objects of level 1 (panelvertical, Title, overflowpanel, etc) then grouping together all of the same name

b) Doing the same in level 2 (..,3,etc) when there is a level 2 (..,3,etc) (Pane1, Pane2, Pane3, etc) then grouping together all of the same name at this level

c) Sorting the properties alphabetically, but keeping the previous object ordering

...I think it's a lot of work, but the aim of the text version of the files is not only allow reassembling the binary, but allow easy diffing too, with minimal to no changes for just saving a file.
VFP sometimes change the order of many things when saving, even if you don't change anything. That's why ordering is important too.

I will think about some options to do this, because this reordering can be complicated.

Thanks.-

**Comment by fdbozzo** [comment]
Hi Jochen!

I've been thinking on this, did some testing and I'm going with your option #1, because keeping the original object order is the most conservative option, inevitably causes some differences with existent generated TX2, but I think it is the safest. 
At the end differences will occur only the first time.

I keep doing some testing, but meanwile I'd upload the modified version, so you can take a look and see if it works for you, if you like.

This is the development branch with foxbin2prg.prg and foxbin2prg.exe:
https://github.com/fdbozzo/foxbin2prg/tree/master-v1.19.51.4

If you find some trouble, please, drop me a line.

Thanks!

**Comment by JochenKauz** [comment]
Hi Fernando,
I will give it a try today and make a comment how it works.
Many, many thanks for your work!
Best regards
JochenKauz

**Comment by JochenKauz** [comment]
Hi Fernando,
did a first test and it seems to work really good. Will do further testing today and check other forms and classes. I will do a complete checkin of my project with text only files into my gitea and then checkout with regenerating all binaries.
I'll give a comment about succes.

Cheers!

**Comment by JochenKauz** [comment]
Hi,
did further testing and it seems to work. I translated our project with 560 scx, 60 vcx and 350 frx to text, put it into gitea and checked it out with regenerating all binaries. I checked the critical forms and classes and all seems to work, a build to exe compiled without error.
Only thing I discovered was a conversion error for a dbf (type 8). But I think it is only a problem of our use of a memo field storing not wellformed text (encrypted text) into it. I can solve this by adding it as a binary to gitea.
Great job and many, many thanks!

Cheers
JochenKauz
