### ISSUE TITLE
Error Log is not being written when there is an error in SCX file...

### ISSUE THREAD

**Issue by mattslay** [fdbozzo/foxbin2prg#30]
I am still exploring the FoxBin2Prg.prg code to see how it works when it finds an error in a SCX or VCX file.

When stepping through the code in debugging mode I was able to find the .c_TextError property for this current error case I had (see text below), but the only problem is that **FoxBin2Prg did not write this code to a log file,** not that I could tell.

After processing the SCX file, the .writeErrorLog_Flush() method was not called because **the property lnCodError was 0, but there really was an error in the SCX file,** as you can see in the .c_TextError property:

.c_TextError property:

```
    2018-11-03T06:20:42  ----------------------------------------------------------------------------------------------------
    ERRORS FOUND IN FILE [C:\Temp\quotes.scx]
    * Duplicated Object "btn_delete_small.formquotes.menutoolbar1.cmdnew" @Recno 74, (1st.Recno:73)
    * Duplicated Object "btn_delete_small.formquotes.menutoolbar1.cmdnew" @Recno 75, (1st.Recno:73)
    * Duplicated Object "btn_delete_small.formquotes.menutoolbar1.cmdnew" @Recno 76, (1st.Recno:73)
    * Duplicated Object "btn_delete_small.formquotes.menutoolbar1.cmdnew" @Recno 77, (1st.Recno:73)

```
(You can test this yourself with the ZIP file I attached in my previous Issue which has the SCX/SCT files which have this error.)

Here is the code that should have written the error log file (see screenshot attachment)

![2018-11-03_6-28-57](https://user-images.githubusercontent.com/309016/47951720-9c64a300-df32-11e8-8022-6fcf9aeadcce.png)

**Comment by fdbozzo** [comment]
Hi Matt!

I think that you are missing some parameters in the call (see https://github.com/fdbozzo/foxbin2prg/wiki).

FoxBin2Prg can work with many use cases, depending on what you want to do, and here are some of them:

1) **As Stand-alone PRG (like old scctext)**: This is what you are using in your example.
In this case you can indicate the file name to convert and all the convertion occurs without warnings or errors shown, because it is the default mode for any unattended process.

2) **As Object**: This is the best choice when you neeed to add FoxBin2Prg as a middle process for being controlled from another processes at low level, like other projects do as Mike Potjer's [VFP Git Utils](https://github.com/mikepotjer/vfp-git-utils) or Lutz Scheffler's [(Bin 2 Text)](https://github.com/lscheffler/bin2text)

3) **As Stand-alone EXE**: This is the best choice for normal use, because it's the fastest option.

**This apply for all use cases:**
When you call FoxBin2Prg with only the file name to convert, then no-messages are shown because it works on unattended-mode, which is the expected behavior for unattended mode. In this mode the only way you have to know if an error did occur is to query the returned code error, and code errors are only returned when calling FoxBin2Prg as a function or as object when using the Execute method.

If you want warnings and error messages to be shown, then you need to use appropiate parameters, as detailed in the wiki and in the included README.MD file, which says this:

You can create up to three different shortcuts pointing to FoxBin2Prg.exe and in your "SendTo" folder in your Windows profile. This allows you to "send" a selected file (pjx,pj2,etc) to the selected option, and make on-the-fly conversions. (Make sure you have the option for seeing known file extensions turned on!):

```
Shortcut Name                | Right-click/Properties/destination          | What you can do with this option
---------------------------- | ------------------------------------------- | --------------------------------
FoxBin2Prg - Binary2Text.lnk | <path>\foxbin2prg.exe "BIN2PRG-SHOWMSG"     | Process directories or individual files
FoxBin2Prg - Text2Binary.lnk | <path>\foxbin2prg.exe "PRG2BIN-SHOWMSG"     | Process directories or individual files
FoxBin2Prg.lnk               | <path>\foxbin2prg.exe "INTERACTIVE-SHOWMSG" | Process individual files or directories asking what to convert
```


The important part here is the "INTERACTIVE-SHOWMSG", which you can reduce to "SHOWMSG" to only see warnings and errors.

Try this parametets and you should see the errors that are not shown by default.
I'd make a test with your form with the PRG and the EXE, and both show this LOG:

```
2018-11-04T13:29:10  ----------------------------------------------------------------------------------------------------
SE HAN ENCONTRADOS ERRORES EN EL ARCHIVO [H:\DESA\foxbin2prg\pruebas varias\v1.19.51\MattSlay\quotes.scx] 
* Objeto Duplicado "btn_delete_small.formquotes.menutoolbar1.cmdnew" @Recno 74, (1st.Recno:73)
* Objeto Duplicado "btn_delete_small.formquotes.menutoolbar1.cmdnew" @Recno 75, (1st.Recno:73)
* Objeto Duplicado "btn_delete_small.formquotes.menutoolbar1.cmdnew" @Recno 76, (1st.Recno:73)
* Objeto Duplicado "btn_delete_small.formquotes.menutoolbar1.cmdnew" @Recno 77, (1st.Recno:73)

```

**Comment by mattslay** [comment]
Thanks for this feedback an info. I will try the things you have suggested to improve my knowledge of this tool. Thanks for this great project!
