### ISSUE TITLE
HomeDir is generated in pj2 file causing git changes every time

### ISSUE THREAD

**Issue by ViliusS** [fdbozzo/foxbin2prg#40]
I'm trying to make sense of foxbin2prg usage scenario in our git workflow.

I have generated pj2 files for our projects, but what I don't understand is why HomeDir, Debug and couple of other settings are still stored in text file? This means that every time different developer regenerates pj2 file it is marked as changed by git. Can something be done about this, or maybe this is a limitation of VFP? 

As far as I understand this VFP parameter is user-defined and should not appear in global settings of the repository for other developers.

**Comment by fdbozzo** [comment]
Hi @ViliusS ,
FoxBin2Prg just converts what is already in the PJX --or any other-- file, so if you open the PJX as a table (because *it is* a table) with USE <yourproject.pjx>, you will see that this values are already there, HomeDir as well as Debug, if checked.
Normally, when other fellow open your project in another directory, VFP autimatically updates the HomeDir with the new one.
If you don't want that this field changes, then what it is normally done, is to set with all developers a naming convention for the directories, so everyone have the project in the same drive, lets say: c:\dev\vfp\yourProject, so it dosn't matter who opens the project in it's own personal folder, being all equals then this field is not already changed, so when generating the PJ2 and comparing with the existent PJ2 file, if there are no differences, then the new one is discarded and the old one is preserved, letting the SCM not detect any changes.
If there are changes, then it is because they really are there.

The same applies with the remaining files (sc2, vc2, mn2, etc)

You can find in the Wiki some help about many useful settings and internals, and you may find the Mike Potjer git utils for FoxBin2Prg useful too, if already not using it:
https://github.com/mikepotjer/vfp-git-utils

Best regards!

**Comment by ViliusS** [comment]
Thank you for your answers @fdbozzo. I understand your idea behind using the same path for all developers but I think that won't be possible, mainly because user (developer) content should be stored under user's profile. This is a requirement when developers are using Terminal Services on Windows Server for their work. Also, keeping user's content not in the profile makes management and security more difficult to implement.

Is there an option in foxbin2prg or a code line which would allow to disable generation of <HomeDir> in text files? I didn't try it yet, but my idea is the following:
1. When a new project is created pj2 files are generated and commited to git without HomeDir attribute.
2. New developer clones repository from git and generates pjx files for their local work.
3. VFP asks to update HomeDir because it doesn't see that attribute in pjx file.
4. After more project files are added the new pj2 file is generated and commited to git repository.
5. All other developers see pj2 changes and updates their copies and regenerates pjx files accordingly. They also set HomeDir again.

Will this work?

I will check vfp-git-utils too. Thank you.

**Comment by DougHennig** [comment]
Hi Fernando.

I agree with @ViliusS: I would rather not have HomeDir in the PJ2 file. Perhaps this could be added as a configuration option.

Doug

**Comment by fdbozzo** [comment]
Hi Doug, nice to read you.
I did not do VFP programming enymore since 3 years now, so anyone can fork and tweak the project for it's own need.
Would be nice if VFPx fork this project and continue improoving it for the rest of the developers that continue using VFP.
I really do not have the time to continue maintaining the project :-(

Best regards!

**Comment by DougHennig** [comment]
Hi Fernando.

OK, will do. Thanks for creating this great tool in the first place!

Doug

**Comment by DougHennig** [comment]
Hi Fernando.

I took your suggestion: I forked the project, added support for a new HomeDir configuration setting (plus a couple of other things), and created a pull request.

Doug

**Comment by mattslay** [comment]
**Doug** - I'm betting your Fork could become the main tool now, since Fernando said he doesn't plan to work on the project any longer, and he's even asking for the VFPx community to take over ownership and development of it .  Perhaps he could make you a Contributor on his repo and then you could handle your own pull requests (and any others) keep the original repo up to date.  Of course, there have been other projects where one of the Forks takes off as the leader in a tool or app, and the original one just sort of gets abandoned.

Perhaps you do not want to assume this responsibility of the main repo?

**Comment by DougHennig** [comment]
@mattslay I'm fine with that -- I use FoxBin2PRG every day and have poked around in the code enough to be familiar with it. I'd rather see this be the main repository since this is where all the links point.

@fdbozzo If you make me a contributor to the repository, I can take care of the existing pull requests and other tasks.

Doug

**Comment by fdbozzo** [comment]
Excelent idea!

Doug, as far I know, you are collaborator since the beginning.
Does this permission allow you to update the repository directly? Please,
check it and let me know:

[image: imagen.png]

**Comment by DougHennig** [comment]
Yes, you are correct. One issue: I cannot merge my own pull request, so please merge my pull request when you get a chance. In the future, I will make changes directly to the repository rather than in a fork so this will not happen again.

**Comment by fdbozzo** [comment]
Hi Doug,

I did approve the PR, but GitHub doesn't let me do the merge directly
because there are manual conflicts to resolve that are too complex to be
made with the web interface (this is what says GitHub in an error message).

Are you able to do the proposed GitHub merge instructions to fix this PR?
If it doesn't allow you to do it, let me know and I see how to do it.

[image: imagen.png]

**Comment by DougHennig** [comment]
I closed the pull request and will do the merge in Git instead.

**Comment by lscheffler** [comment]
@DougHennig    
If you like to avoid the merge with my fork, let me know. As I saw, it was not that much, and I can add to the docs as well. I'm good into it for now. :)

**Comment by DougHennig** [comment]
@fdbozzo I had to merge @lscheffler changes manually but when I try to push to the repository, I get:

remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.

Can you change the repository so that I can push changes directly? Thanks.

Doug

**Comment by fdbozzo** [comment]
Hi Doug,

The pull-request (#43) says "*Review required*".
Aren't you able to approve it? AFAI understand, I think that you should
approve the PR so you can later do the manual merge, but I'm not sure.

Can you confirm this, Doug?

**Comment by DougHennig** [comment]
Hi Fernando.

I did approve it but I had to do the merge manually (that is, in my local repository) and I get the error I mentioned when I try to push to GitHub. Also, I will not be able to push changes I make to a clone of the repository, only through a fork, if the repository is marked as protected.

Doug

**Comment by fdbozzo** [comment]
Ok, this is what I've found:

There is one default protection rule (I think that GitHub do this for every
repo), with this configuration applicable to *master*:

Protect matching branches:
Require pull request reviews before merging > require approving reviews: 1

Rules applied to everyone including administrators:
Allow force pushes (*now it is checked*)


My comments:
The only protection was the "1 reviewer" requirement, but I did check
"Allow force pushes" so --I think-- you can now do the push with the force
option.

Let me know if you can do it now.

**Comment by DougHennig** [comment]
No, I still get the same error when I use:

git push origin master --force

**Comment by fdbozzo** [comment]
I reply to this on issue #43, where it belongs, Doug.

**Comment by DougHennig** [comment]
OK, thanks.

**Comment by ViliusS** [comment]
If you are still struggling with GitHub let me shed some light.

GitHub by default requires 1 *other* reviewer to approve any PRs even from administrators. If you don't need this behavior then you can uncheck "Require pull request reviews before merging" checkbox. You should leave "Allow force pushes" disabled. It is unrelated option and could allow pushes which leaves repository in a permanent out of sync state for all other forks/local repositories.

The correct way to do this in your case would be to transfer repository ownership to Doug, or make him repository administrator so that he could commit to master directly, and then *uncheck* "Include administrators" in the "Protected branches" options.

**Comment by DougHennig** [comment]
@ViliusS The latest build has a HomeDir setting in the CFG file. Set it to 0 to prevent HomeDir from being written to the PJ2 file.

Doug
