### ISSUE TITLE
After vc2 convert back to vcx class is corrupted no errors reported

### ISSUE THREAD

**Issue by bjornhoeksel** [fdbozzo/foxbin2prg#78]
## ℹ Computer information

- VFP version:  9 sp2
- FoxBin2PRG version: latest
- Last FoxBin2PRG version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

After vc2 convert back to vcx class is corrupted no errors reported

problem caused by code:

	Procedure ignoreCorruptedObjects(lcCursor)
* Issue#17 - Error, The specified key already exists
* Para evitar este error se deben ignorar los objetos corruptos (duplicados)
* Se identifican porque la clase principal el campo Reserved1 tiene vacio en vez de "Class"
		Local lcParentObjName, lcSetDeleted
		Select (lcCursor)
		lcSetDeleted	= Set("Deleted")
		Set Deleted Off

		Scan For PLATFORM = "WINDOWS" And Empty(Parent) And Empty(RESERVED1)
			lcParentObjName	= Lower(OBJNAME)
			Delete
			Skip
			Delete Rest While Getwordnum(Lower(Parent) + '.', 1, '.') == lcParentObjName
			Skip -1
		Endscan

		Set Deleted &lcSetDeleted.
		Return
	Endproc

suggested fix:

	Procedure ignoreCorruptedObjects(lcCursor)
* Issue#17 - Error, The specified key already exists
* Para evitar este error se deben ignorar los objetos corruptos (duplicados)
* Se identifican porque la clase principal el campo Reserved1 tiene vacio en vez de "Class"
		Local lcParentObjName, lcSetDeleted
		Select (lcCursor)
		lcSetDeleted	= Set("Deleted")
		Set Deleted Off

		Scan For PLATFORM = "WINDOWS" And Empty(Parent) And Empty(RESERVED1)
			lcParentObjName	= Lower(OBJNAME)
			Delete
			**IF (NOT EMPTY(lcParentObjName))**	
				Skip
				Delete Rest While Getwordnum(Lower(Parent) + '.', 1, '.') == lcParentObjName
				Skip -1
			**ENDIF**	
		Endscan

		Set Deleted &lcSetDeleted.
		Return
	Endproc

### ✔️ Expected result

a valid vcx with all classes

### ❌ Actual result

corrupt vcx missing classes. this is reported bij vfp when open in a class browser

**Comment by lscheffler** [comment]
Please post an example (VCX, VCT, VC2). If not possible in open, just let me know your contact info.

**Comment by bjornhoeksel** [comment]
> Please post an example (VCX, VCT, VC2). If not possible in open, just let me know your contact info.

After converting vc2 back to vcx the vcx is missing classes and gives errors when opening in class browser
[ac1_dlg.VC2.txt](https://github.com/fdbozzo/foxbin2prg/files/8131559/ac1_dlg.VC2.txt)

**Comment by lscheffler** [comment]
## Analysing
Running FoxBin2Prg against your VC2 never reached _ignoreCorruptedObjects_   

Analysing your vc2 I found the following problem(s):   
- The class **ac1_msg_client_question** is defined as `DEFINE CLASS ac1_msg_client_question AS ac1_msg_client OF "ac1_dlg.vcx"`
-- The class **ac1_msg_send_notification** is defined as `DEFINE CLASS ac1_msg_send_notification AS ac1_msg_client OF "ac1_dlg.vcx"`   
There is no class **ac1_msg_client** in the _ac1_dlg.vc2_, and in the resulting _ac1_dlg.vcx_. This is why the class browser can not display it. For FoxBin2Prg there is no error, since it just moves the class from the text into the vcx using table commands, not class modifying ones.   
The VCX is in a perfect state from foxBin2Prg view point. Even for VFP it might run, as long as **ac1_msg_client** class is found in a different lib defined for example witt _SET CLASSLIB_
- The message in the class browser, while cryptic, points to the parent class problem.
## Conclusion
The problem is in
- the original lib
-  transforming the original lib to text   
For the later I would need the original VCX
## Tip
If the problem is in the original lib, and the class **ac1_msg_client** is defined somewhere else, hack the VCX and change _classloc_ field to the real lib file for the two records. If you dislike hacking the vcx, you might just alter the respective lines in the vc2 and recreate the vcx. Even altering the classloc to a non existing file, like `DEFINE CLASS ac1_msg_client_question AS ac1_msg_client OF "ac1_dlg_x.vcx"`, will make the class available in the class browser where you might use the class browsers tools to change parent class. Anyway, all three ways are the same.

**Comment by bjornhoeksel** [comment]
> **IF (NOT EMPTY(lcParentObjName))**	
>   		Skip
>   		Delete Rest While Getwordnum(Lower(Parent) + '.', 1, '.') == lcParentObjName
>   		Skip -1
>   	**ENDIF**

No problem is in de code below.  

  Scan For PLATFORM = "WINDOWS" And Empty(Parent) And Empty(RESERVED1)
  	lcParentObjName	= Lower(OBJNAME)
  	Delete
  	Skip
  	Delete Rest While Getwordnum(Lower(Parent) + '.', 1, '.') == lcParentObjName
  	Skip -1
  Endscan

when I run it with new exe build with code with extra if check. then convert works fine. and all my other vcx are converting good as well without this adjustment some of our vcx end corrupted or missing classes. maybe run the code with debug with the vc2 I send before. Its difficult to send a better example.

Code that works:
  Scan For PLATFORM = "WINDOWS" And Empty(Parent) And Empty(RESERVED1)
  	lcParentObjName	= Lower(OBJNAME)
  	Delete
  	IF (NOT EMPTY(lcParentObjName))	
  		Skip
  		Delete Rest While Getwordnum(Lower(Parent) + '.', 1, '.') == lcParentObjName
  		Skip -1
  	ENDIF	
  Endscan

**Comment by lscheffler** [comment]
Ok, the problem is in converting the _vcx_ to _vc2_, not the other way around. Please check the _vc2_ file for class **ac1_msg_client**, it should be there but isn't. We agree that the class is in the _vcx_.
The _vcx_ seems corrupted.   
Checking the _vcx_ using _USE_ and _BROWSE_, I can see there is an oddness in class **ac1_msg_client**. Go to Records 95 to 98

The records 95,96 are not defined, as they should be. (see the class above, any class is the record following not so unique **UniqueID*=="RESERVED'** to (including) the next occurrence of this ID, the order of records defines ZOrder) Deleting those two records in the _vcx_ will create the **ac1_msg_client** in the _vc2_, and the result of the recreation will be fine.

-----
So maybe the change you mention removes just those two lines while **creating** the _vc2_. I have no time to follow this yet, I will check later.

**Comment by bjornhoeksel** [comment]
> Ok, the problem is in converting the _vcx_ to _vc2_, not the other way around. Please check the _vc2_ file for class **ac1_msg_client**, it should be there but isn't. We agree that the class is in the _vcx_. The _vcx_ seems corrupted. Checking the _vcx_ using _USE_ and _BROWSE_, I can see there is an oddness in class **ac1_msg_client**. Go to Records 95 to 98
> 
> The records 95,96 are not defined, as they should be. (see the class above, any class is the record following not so unique __UniqueID_=="RESERVED'_* to (including) the next occurrence of this ID, the order of records defines ZOrder) Deleting those two records in the _vcx_ will create the **ac1_msg_client** in the _vc2_, and the result of the recreation will be fine.
> 
> So maybe the change you mention removes just those two lines while **creating** the _vc2_. I have no time to follow this yet, I will check later.

Hi
We have some vcx files that give problems with this code when lcParentObjName = "" and code seems to deletes random reccords in that situation. The vcx if i complile it with compile classlib i have no errors. In the comment above the problem code is the following mentioned

	Procedure ignoreCorruptedObjects(lcCursor)
* Issue#17 - Error, The specified key already exists
* Para evitar este error se deben ignorar los objetos corruptos (duplicados)
* Se identifican porque la clase principal el campo Reserved1 tiene vacio en vez de "Class"

But for us this code creates problems and missing classes when lcParentObjName is empty. 
When i fix it by not keep delting if lcParentObjName is empty all works ok.

**Comment by lscheffler** [comment]
@bjornhoeksel, I understand the problem. In general, VFP is sometimes odd what works and what not. _FoxBin2PRG_ parses the _vcx_ as a table and assumes some things. For what ever reason, some of your VCX's are not in perfect order (do you use something non build in to work with classes?).   
_FoxBin2PRG_ just fails (without your change) to find those classes in the _vcx_ and skip to the next class, so the class is missing in the _vc2_. A class not in the _vc2_ can not be recreated, and then you got problems.    
If your fix is working, it will generate uncorrupted _vcx_ files and all is good after first recreate. So in this sense it will repair the _vcx_.

I just need to think through your fix, and I need time to push it anyway. It will be done this weekend.
