### ISSUE TITLE
.MN2 to .MNX doesn't re-gen PICTRES or KEY clauses on DEFINE BAR

### ISSUE THREAD

**Issue by DanLauer** [fdbozzo/foxbin2prg#83]
## ℹ Computer information

- VFP version:  VFP9SP2
- FoxBin2PRG version: 1.9.73
- Last FoxBin2PRG version w/o bug (if available): 1.9.51 (my experience...didn't have interim builds)

## 📝 Provide detailed reproduction steps (if any)

1. Generate .MNX from .MN2 files that contain PICTRES or KEY clauses on DEFINE BAR

### ✔️ Expected result

.MNX should have these options defined.

### ❌ Actual result

.MNX no longer has these options defined.

## 📷 Config

[FoxBin.zip](https://github.com/fdbozzo/foxbin2prg/files/8636665/FoxBin.zip)

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/2616544/167045130-ce887448-3dcd-44c1-a37d-305a651e5faf.png)

**Comment by bjornhoeksel** [comment]
Menu bars with shortcuts keys like KEY F6, "F6"; are lost.
This problem is caused by the fix I made for https://github.com/fdbozzo/foxbin2prg/issues/80 
See sys_men.mn2 key F6 is lost when converted back to mnx
That fix contains a problem.  I send a new foxbin2prg.prg that fixes this problem @lscheffler  can you patch this? 
[sys_men.mn2.txt](https://github.com/fdbozzo/foxbin2prg/files/8661346/sys_men.mn2.txt)

[foxbin2prg.prg.txt](https://github.com/fdbozzo/foxbin2prg/files/8661437/foxbin2prg.prg.txt)

**Comment by lscheffler** [comment]
Done, Thor is updated
