### ISSUE TITLE
Text2Bin on PJX errors out for projects with an attach icon that has a drive letter on its path.

### ISSUE THREAD

**Issue by ericbarte** [fdbozzo/foxbin2prg#93]
## ℹ Computer information

- VFP version: 9
- FoxBin2PRG version: 1.19.76
- Last FoxBin2PRG version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. Create a new project.
2. Go to Project > Project Info > Attach Icon.
3. Choose an icon that's from a different drive.
4. Do a Bin2Text to create the PJ2 file.
5. Do a Text2Bin. Errors out.

### ✔️ Expected result

It should regenerate the PJX/T files.

### ❌ Actual result

Error log has "Error 202, Invalid path or file name."

## 📷 Config

**Do not include your normal config.**
Please add your current full configuration.   
Create a config file via `DO FOXBIN2PRG.PRG WITH '-C','path-to-source\FoxBin.cfg'` , zip and add here.  

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by lscheffler** [comment]
@ericbarte The icon is stored in the form   
`	.Icon = lcCurdir + 'd:\Path\my.ico'`   
Obviously this will fail.   

----
I fear it will not help you, but FoxBin2Prg is not designed to operate this way. It's clearly set up to deal with the classical mode where all the sources are in the directory or subdirectories of the place where the pjx is stored.   
Since the project is made to deal with source control, it's impossible to tell where (on which drive) a project will be recreated.   The use of drive letters makes no sense under this circumstance. And, from a source control POV, I have no idea how to include such a file into a source control at all.   
I agree that it should not fail and possibly deny to create the text file in the first place, but your problem is true to any file stored in the PJX, not only the icon of the project.   

To fix your problem, I suggest that you open the pj2 with an editor of your choice, look up the icon and remove the whole line. You can try to remove the `lcCurdir +`   part and look if it recreates the pjx.   
If you really need this function I suggest to fork the project.

----
*NOTE: If you choose to have binary tables outside the path given by your project, the result of FoxBin2PRG might be unexpected, since the config files are valid for there folder and subfolders, not for a project.*

**Comment by lscheffler** [comment]
@ericbarte  See [this](https://github.com/fdbozzo/foxbin2prg/blob/master/docs/FoxBin2Prg_Internals.md#storing-paths-for-pjx) how to solve your problem with the new version.
