### ISSUE TITLE
Question about <PropValue> comments in .xx2 files

### ISSUE THREAD

**Issue by RickBorup** [fdbozzo/foxbin2prg#94]
Do you know at which version the `*<PropValue>` and `*</PropValue>` comment tags were introduced (or removed) from FoxBin2PRG? I'm working with a team where not all developers are using the same version of FoxBin2PRG. When sharing files via Git, differences are sometimes detected in the .xx2 files which turn out to be merely the presence or absence of these comment tags. We are speculating it's due to different versions of FoxBin2PRG and would like to standardize to eliminate this issue.

**Comment by lscheffler** [comment]
@RickBorup, this a change to fix #90, #91 #92, where data in the properties was lost. This is fixed in [v1.19.77](https://github.com/fdbozzo/foxbin2prg/releases/tag/v1.19.77) with the coast of a different structure of the [vs]c2 files. You will only loose data in the situations of the issues mentioned, else it's just a pain with the commits.
Sorry, I thought I put a message about this somewhere.

Anyway, I recommend to use the latest version [v1.19.78](https://github.com/fdbozzo/foxbin2prg/releases/tag/v1.19.78), available via this repository or Thor.

Additionally I like to point you to [Bin2Text](https://github.com/lscheffler/bin2text), this will only convert files changed, so files untouched by VFP will not be transformed to text. But it might be a different logic of git use.

**Comment by RickBorup** [comment]
@lscheffler Got it. Thanks for the quick reply.
