### ISSUE TITLE
Getting "No table is open" error in version 79 with ChilkatVCX

### ISSUE THREAD

**Issue by billand88** [fdbozzo/foxbin2prg#98]
## ℹ Computer information

- VFP version: Visual FoxPro 09.00.0000.7423 for Windows [Feb 23 2009 13:20:28] Product ID 76683-211-9836745-18834
- FoxBin2PRG version: EXE Version: v1.19.79
- Last FoxBin2PRG version w/o bug (if available): I'm pretty sure version 78 worked for me...

## 📝 Provide detailed reproduction steps (if any)

First of all, I need to relearn FoxBin2Prg every time I run a ChilkatVFP update. That's not your problem, that's mine :). The point here is I could be doing something completely dumb.

Anyway, one of the last things I do when prepping a ChilkatVFP update is to set the directory to the FoxBin2Prg directory and run FoxBin2Prg against the ChilkatVFP class library. With version 79 all I get is a "No table is open in the current work area." message.

I've been sitting on an update for at least a couple of weeks but since I'm not finding debugging time I'll throw it up here.

1. Here's what I'm running: DO FOXBIN2PRG.PRG WITH [d:\shares\drv_data\vfpapps\chilkat\chilkat.vcx]
2. Boom!
3. …

### ✔️ Expected result: Compilation

Normal output file.

### ❌ Actual result

Error 52, No table is open in the current work area.
convert, 16986
SET NOCPTRANS TO ole

Recno: 0
.............................................
FoxBin2Prg: [C:\USERS\BILLADMIN\DOCUMENTS\GITHUB\FOXBIN2PRG\FOXBIN2PRG.FXP] (EXE Version: v1.19.79)
tc_InputFile = [D:\SHARES\DRV_DATA\VFPAPPS\CHILKAT\CHILKAT.VCX]

Source file: D:\Shares\Drv_Data\VFPAPPS\ChilKat\chilkat.vcx

## 📷 Config

[FOXBIN.zip](https://github.com/fdbozzo/foxbin2prg/files/12432164/FOXBIN.zip)
[chilkat.zip](https://github.com/fdbozzo/foxbin2prg/files/12432200/chilkat.zip)

**Comment by lscheffler** [comment]
@billand88 Yes, this is a bug. If you are using CODEPAGE 1252, run `?CPCURRENT()`, please comment all lines with SET NOCPTRANS and run as usual. The fix is in progress. I hope to post it this week.

---
If you run `DO FOXBIN2PRG.PRG` without parameter, a help screen should come up. Also check the docu here.   
I recommend an interface tool for FoxBin2Prg, Thor offers some. If you are not using Thor, check [Bin2Text](https://github.com/lscheffler/bin2text). It will not turn on it's git parts if git is not installed, but you can use it to run FoxBin2Prg via interface.

**Comment by billand88** [comment]
>> _...please comment all lines with SET NOCPTRANS and run as usual_ <<

That worked!

Thanks,

Bill Anderson

**Comment by lscheffler** [comment]
This is to #87 and #96 , where FoxBin2Prg has problems with non standard CodePage, and the fix went wrong.

**Comment by lscheffler** [comment]
Fixed version is available at https://github.com/lscheffler/foxbin2prg, no Thor update provided.
